DROP TABLE IF EXISTS covs;

CREATE TABLE covs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    formula TEXT NOT NULL,
    tipo TEXT NOT NULL,
    kcl DECIMAL,
    koh DECIMAL,
    logkCl DECIMAL,
    logkOH DECIMAL,
    enlace TEXT NOT NULL
);